name: CICD using Maven and tomcat
on:
 push:  # run when there is commit to repo
 workflow_dispatch:  # run manually
jobs:
 CICDjob:
   runs-on: ubuntu-latest
   steps:
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - name: Connect to Lab machine and Deploy the code on tomcat9 
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: '13.235.134.109'
        user: 'labuser'
        pass: 'Nuvelabs123$'
        port: 22
        connect_timeout: 60s   
        first_ssh: |
          sudo chmod 777 /var/lib/tomcat9/webapps
        scp: |
          './target/*war' => /var/lib/tomcat9/webapps
        last_ssh: |
          sudo systemctl restart tomcat9
